import { createTheme, Theme } from '@mui/material/styles'

export const EXTRA_COLORS_PALETTE = Object.freeze({
	OFFICIAL_BACKGROUND: 'white',
	OFFICIAL_BACKGROUND_DARK: 'rgba(248, 248, 248, 1)',
	WINNER_MAIN: '#161A39',
	TEXT_MAIN: '#33364C',
	TEXT_GREY_MAIN: 'rgba(132, 133, 148, 0.85)',
	PANEL_BG_MAIN: '#DCDDFB',
	PANEL_BG_LIGHT: '#F0F0FE',
	LIGHT_BLUE: '#F0F0FF',
	INFO_ICON_MAIN: '#AEB1F3',
	COUNTER_PANEL_DARK_BLUE_BG: '#DCDCFE',
	COUNTER_PANEL_DARK_BLUE_PRIMARY: '#5C5CD6',
	COUNTER_PANEL_DARK_BLUE_SECONDARY: 'rgba(127,127,235,0.3)',
	COUNTER_PANEL_AQUA_BG: '#D6FDF7',
	COUNTER_PANEL_AQUA_PRIMARY: '#36C7E0',
	COUNTER_PANEL_AQUA_SECONDARY: '#AFFBF5',
	LIGHT_GREY: '#f8f8f8',
	OFFLINE_GREY: '#848594',
	DEFAULT_BORDER_COLOR_GREY: '#F1F0F3',

	TOAST_SUCCESS_MAIN: '#02E073',
	TOAST_ERROR_MAIN: '#FF384B',
	TOAST_WARNING_MAIN: '#FFDF82',
	TOAST_INFO_MAIN: '#307AE0',

	BACKDROP_COLOR: '#08085966',
	BACKDROP_Z_INDEX: 5,

	SECONDARY: {
		LIGHT: '#AFAFF8',
		MAIN: '#2E2EBD',
		DARK: '#1C299B',
	},
	INFO: {
		MAIN: '#151834DF',
	},

	GREY: {
		50: '#100b370f',
	},
})

export const EXTRA_CONST_MEASUREMENTS = Object.freeze({
	BOX_RADIUS: 16,
	BOX_SHADOW: '0px 8px 24px rgba(52, 54, 78, 0.15)',
})

export const themeOptions: Theme = createTheme({
	typography: {
		fontFamily: ['Inter', 'Arial'].join(','),
	},
	palette: {
		primary: {
			light: EXTRA_COLORS_PALETTE.TEXT_MAIN,
			main: EXTRA_COLORS_PALETTE.TEXT_MAIN,
			dark: EXTRA_COLORS_PALETTE.TEXT_MAIN,
		},
		secondary: {
			light: EXTRA_COLORS_PALETTE.SECONDARY.LIGHT,
			main: EXTRA_COLORS_PALETTE.SECONDARY.MAIN,
			dark: EXTRA_COLORS_PALETTE.SECONDARY.DARK,
		},
		info: {
			light: EXTRA_COLORS_PALETTE.TEXT_GREY_MAIN,
			main: EXTRA_COLORS_PALETTE.INFO.MAIN,
		},
		background: {
			default: EXTRA_COLORS_PALETTE.OFFICIAL_BACKGROUND,
			paper: EXTRA_COLORS_PALETTE.OFFICIAL_BACKGROUND_DARK,
		},
		grey: {
			50: EXTRA_COLORS_PALETTE.GREY['50'],
		},
	},
})
